import Link from "next/link";
import Layout from "../components/Layout";
import { getAllPosts } from "../lib/mdx";

export default function BlogList({ posts }) {
  return (
    <Layout>
      <h1>All Posts</h1>
      <p>
        Click the link below to navigate to a page generated by{" "}
        <code>mdx-bundler</code>.
      </p>
      <ul>
        {posts.map((post, index) => (
          <li key={index}>
            <Link href={`blog/${post.slug}`}>{post.frontmatter.title}</Link>
          </li>
        ))}
      </ul>
    </Layout>
  );
}

export const getStaticProps = async () => {
  const posts = getAllPosts();

  return {
    props: { posts },
  };
};
