import Link from 'next/link';
import Container from '../components/Container';
import { getAllPosts } from '../lib/mdx';

export default function BlogList({ posts }) {
  return (
    <Container>
      <h1>Hei vaan kaikille</h1>
      <p>
        Click the link below to navigate to a page generated by <code>mdx-bundler</code>.
      </p>
      <ul>
        {posts.map((post, index) => (
          <li key={index}>
            <Link href={`/blog/${post.slug}`}>{post.frontmatter.title}</Link>
          </li>
        ))}
      </ul>
    </Container>
  );
}

export const getStaticProps = async () => {
  const posts = getAllPosts();

  return {
    props: { posts },
  };
};
